apps/mascota/urls.py
from django.conf.urls import url,include
from django.contrib.auth.decorators import login_required
from apps.mascota.views import listadousuarios, index,mascota_view,mascota_list,mascota_edit,mascota_delete, \
MascotaList,MascotaCreate,MascotaUpdate,MascotaDelete

from . import views

urlpatterns = [
    url(r'^index$', views.index, name='index'),
    url(r'^nuevo/$', login_required(MascotaCreate.as_view()), name='mascota_crear'),
    url(r'^listar/', login_required(MascotaList.as_view()), name='mascota_listar'),
    url(r'^editar/(?P<pk>[\w-]+)/$', login_required(MascotaUpdate.as_view()), name='mascota_editar'),      #'^editar/(?P<cadena>[\w-]+)/$' TEXTO otro <folio>[\w-]+>
    url(r'^eliminar/(?P<pk>[\w-]+)/$', login_required(MascotaDelete.as_view()), name='mascota_eliminar'),#'^editar/(?P<numero>\d+)/$'     NUMERO
    url(r'^listado/', listadousuarios, name="listado"),

]

refugio/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete,logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^adopcion/', include('apps.adopcion.urls',namespace='adopcion')),
    url(r'^mascota/', include('apps.mascota.urls',namespace='mascota')),
    url(r'^usuario/', include('apps.usuario.urls', namespace='usuario')),
    url(r'^accounts/login/',login, {'template_name':'index.html'},name = 'login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset,
        {'template_name': 'registration/password_reset_form.html',
         'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^reset/password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
    #url(r'^', include('path_to_your_apps.minsalogin.urls', namespace='auth')),

]# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/mascota/models.py
from django.db import models
import datetime

# Create your models here.
from django.utils import timezone
from apps.adopcion.models import Persona

class Vacuna(models.Model):
	nombre=models.CharField(max_length=50)
	
	def __str__(self):
		return '{}'.format(self.nombre)

class Mascota(models.Model):
	folio= models.CharField(max_length=10,primary_key=True)
	nombre = models.CharField(max_length=50)
	sexo=models.CharField(max_length=10)
	fecha_rescate = models.DateField(null=True,blank=True)
	edad_aproximada = models.IntegerField(null=True,blank=True)
	fecha_registro = models.DateField(auto_now_add=True)#timezone.now --> DatetimeField-----datetime.date.today
	persona=models.ForeignKey(Persona,null=True,blank=True,on_delete=models.CASCADE)
	vacuna=models.ManyToManyField(Vacuna)

	def __str__(self):
		return '{}'.format(self.nombre)

	#def publish(self):
		#self.fecha_registro = timezone.now()
		#self.save()

apps/mascota/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.contrib.auth.models import User

# Create your views here.
from django.http import HttpResponse
from django.core import serializers
from apps.mascota.form import MascotaForm
from apps.mascota.models import Mascota
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
#import pdb

def listadousuarios(request):
	lista = serializers.serialize('json', User.objects.all(), fields=['username', 'first_name'])
	return HttpResponse(lista, content_type='application/json')

def index(request):#pdb.set_trace()
    return render(request,'mascota/index.html')

def mascota_view(request):
    if request.method=='POST':
        form=MascotaForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            print(form.errors)
            return redirect('mascota:mascota_listar')
    else:
        form=MascotaForm()
    return render(request,'mascota/mascota_form.html',{'form':form})

def mascota_list(request):
    #import pdb
    #pdb.set_trace()
    mascota=Mascota.objects.all().order_by("folio")
    contexto={'mismascotas':mascota}
    return render(request,'mascota/mascota_list.html',contexto)

def mascota_edit(request,folio):
    mascota=Mascota.objects.get(folio=folio)
    if request.method=='GET':
        form=MascotaForm(instance=mascota)
    else:
        form=MascotaForm(request.POST,instance=mascota)
        if form.is_valid():
            form.save()
        return redirect('mascota:mascota_listar')
    return render(request,'mascota/mascota_form.html',{'form':form})

def mascota_delete(request,folio):
    mascota=Mascota.objects.get(folio=folio)
    if request.method=='POST':
        mascota.delete()
        form=MascotaForm(instance=mascota)
        return redirect('mascota:mascota_listar')
    return render(request,'mascota/mascota_delete.html',{'mascota':mascota})

class MascotaList(ListView):
    model=Mascota
    template_name='mascota/mascota_list.html'
    paginate_by=2


class MascotaCreate(CreateView):
    model = Mascota
    form_class=MascotaForm
    template_name='mascota/mascota_form.html'
    success_url=reverse_lazy('mascota:mascota_listar')

class MascotaUpdate(UpdateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar')

class MascotaDelete(DeleteView):
    model = Mascota
    template_name = 'mascota/mascota_delete.html'
    success_url = reverse_lazy('mascota:mascota_listar')

apps/templates/mascota/index.html
{% extends 'base/base.html' %}
{% block header %}header de mascota {% endblock %}
{% block title %}MASCOTAS {% endblock %}

apps/templates/mascota/mascota_delete.html
{% extends 'base/base.html' %} 

{% block content %}
<form method="post">
	{% csrf_token %}
	<h2>¿Desea eliminar el registro de {{object.nombre}}?</h2>
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class="btn btn-default" href="{% url 'mascota:mascota_listar'%}">Cancelar</a>
</form>
{% endblock %}

apps/templates/mascota/mascota_form.html
{% extends 'base/base.html' %} 

{% block content %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type=submit>Guardar</button>
</form>
{% endblock %}

apps/templates/mascota/mascota_list.html
{% extends 'base/base.html' %} 

{% block content %}

<table class="table table-bordered">
    <thead>
        <tr>
            <td>#</td>
            <td>Nombre</td>
            <td>Sexo</td>
            <td>Fecha de Rescate</td>
            <td>Edad aproximada</td>
            <td>Fecha de Registro</td>
            <td>Adoptante</td>
            <td>Vacuna</td>
            <td>Función</td>
            
        </tr>

    </thead>
    <tbody>
        {% if object_list %}
        {% for mascota in object_list %}
        <tr>
            <td>{{mascota.folio}}</td>
            <td>{{mascota.nombre}}</td>
            <td>{{mascota.sexo}}</td>
            <td>{{mascota.fecha_rescate}}</td>
            <td class="text-center">{{mascota.edad_aproximada}}</td>
            <td>{{mascota.fecha_registro}}</td>
            <td>{{mascota.persona.nombre}} {{mascota.persona.apellidos}}</td>
            <td><ul>{% for objvacuna in mascota.vacuna.values %}
                <li>{{objvacuna.nombre}}</li>
                {% endfor %}</ul>
            </td>
            <td>
            <a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.folio %}">Editar</a>
            <a class="btn btn-danger" href="{% url 'mascota:mascota_eliminar' mascota.folio %}">Eliminar</a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <h1>No hay registros de Mascotas</h1>
        {% endif %}
    </tbody>
</table>
<a button class="btn btn-primary" href="{% url 'mascota:mascota_crear' %}">Crear </button></td></a>
{% endblock %}