apps/adopcion/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login_required

from apps.adopcion.views import index, SolicitudList, SolicitudCreate, SolicitudUpdate, \
    SolicitudDelete

urlpatterns = [
    url(r'^index$', index),
    url(r'^solicitud/listar$', SolicitudList.as_view(), name='solicitud_listar'),
    url(r'^solicitud/nueva$', SolicitudCreate.as_view(), name='solicitud_crear'),
    url(r'^solicitud/editar/(?P<pk>[\w-]+)/$', SolicitudUpdate.as_view(), name='solicitud_editar'),
    url(r'^solicitud/eliminar/(?P<pk>[\w-]+)/$', SolicitudDelete.as_view(), name='solicitud_eliminar'),

    ]

apps/mascota/urls.py
from django.conf.urls import url,include
from django.contrib.auth.decorators import login_required
from apps.mascota.views import listadousuarios, index,mascota_view,mascota_list,mascota_edit,mascota_delete, \
MascotaList,MascotaCreate,MascotaUpdate,MascotaDelete

from . import views

urlpatterns = [
    url(r'^index$', views.index, name='index'),
    url(r'^nuevo/$', login_required(MascotaCreate.as_view()), name='mascota_crear'),
    url(r'^listar/', login_required(MascotaList.as_view()), name='mascota_listar'),
    url(r'^editar/(?P<pk>[\w-]+)/$', login_required(MascotaUpdate.as_view()), name='mascota_editar'),      #'^editar/(?P<cadena>[\w-]+)/$' TEXTO otro <folio>[\w-]+>
    url(r'^eliminar/(?P<pk>[\w-]+)/$', login_required(MascotaDelete.as_view()), name='mascota_eliminar'),#'^editar/(?P<numero>\d+)/$'     NUMERO
    url(r'^listado/', listadousuarios, name="listado"),

]

refugio/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete,logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^adopcion/', include('apps.adopcion.urls',namespace='adopcion')),
    url(r'^mascota/', include('apps.mascota.urls',namespace='mascota')),
    url(r'^usuario/', include('apps.usuario.urls', namespace='usuario')),
    url(r'^accounts/login/',login, {'template_name':'index.html'},name = 'login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset,
        {'template_name': 'registration/password_reset_form.html',
         'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^reset/password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
    #url(r'^', include('path_to_your_apps.minsalogin.urls', namespace='auth')),

]# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<title>{% block title %}REFUGIO DE ANIMALES{% endblock %}</title>
	<meta charset="utf-8" />
    
</head>
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">


        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/app.css' %}">

        
<body>
<div class="container">

	{% block navbar %}
		<div class="bs-docs-section clearfix">
		    <div class="row">
		        <div class="col-lg-12">
		            <div class="bs-component">
		            	<nav class="navbar navbar-default">
		                	<div class="container-fluid">
		                  		<div class="navbar-header">
		                    		<a class="navbar-brand" href="#">Home</a>
		                  		</div>
		                  	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		                    	<ul class="nav navbar-nav">
		                      		<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Mascotas <span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
				                        	<li><a href="{% url 'mascota:mascota_crear' %}">Registrar</a></li>
				                        	<li><a href="{% url 'mascota:mascota_listar' %}">Listar</a></li>
				                        </ul>
		                      		</li>
			                        <li class="dropdown">
			                        	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Adopciones<span class="caret"></span></a>
			                        	<ul class="dropdown-menu" role="menu">
				                          	<li><a href="{% url 'adopcion:solicitud_crear' %}">Solicitar</a></li>
				                          	<li><a href="{% url 'adopcion:solicitud_listar' %}">Listar solicitudes</a></li>
			                        	</ul>
			                        </li>
		                    	</ul>
		                    	<ul class="nav navbar-nav navbar-right">
		                        	<li class="dropdown"><a href="http://codigofacilito.com" onclick="pageTracker._link(this.href); return false;">*</a>
		                        	</li>
		                        	<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
		                        		<ul class="dropdown-menu" role="menu">
		                          			<li><a href="{% url 'logout' %}">Salir</a></li>
		                        		</ul>
		                      		</li>
		                    	</ul>
		                    </div>
		                </div>
		            </nav>
		        </div>
           	</div>
        </div>
    </div>

	{% endblock %}


	{% block content %}
	<h4>	Bloque de contenido		</h4>
	{% endblock %}


	{% block footer %}
	{% endblock%}
</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

	{% block extrajs %}
	{% endblock %}

</body>
        <script>scr="js/jquery.js"</script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
</html


