apps/adopcion/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login_required

from apps.adopcion.views import index, SolicitudList, SolicitudCreate, SolicitudUpdate, \
    SolicitudDelete

urlpatterns = [
    url(r'^index$', index),
    url(r'^solicitud/listar$', SolicitudList.as_view(), name='solicitud_listar'),
    url(r'^solicitud/nueva$', SolicitudCreate.as_view(), name='solicitud_crear'),
    url(r'^solicitud/editar/(?P<pk>[\w-]+)/$', SolicitudUpdate.as_view(), name='solicitud_editar'),
    url(r'^solicitud/eliminar/(?P<pk>[\w-]+)/$', SolicitudDelete.as_view(), name='solicitud_eliminar'),

    ]

refugio/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete,logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^adopcion/', include('apps.adopcion.urls',namespace='adopcion')),
    url(r'^mascota/', include('apps.mascota.urls',namespace='mascota')),
    url(r'^usuario/', include('apps.usuario.urls', namespace='usuario')),
    url(r'^accounts/login/',login, {'template_name':'index.html'},name = 'login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset,
        {'template_name': 'registration/password_reset_form.html',
         'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^reset/password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
    #url(r'^', include('path_to_your_apps.minsalogin.urls', namespace='auth')),

]# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/adopcion/models.py
from django.db import models

# Create your models here.

class Persona(models.Model):
	nombre =models.CharField(max_length=50)
	apellidos =models.CharField(max_length=50)
	edad =models.IntegerField()
	telefono =models.CharField(max_length=12)
	correo=models.EmailField()
	domicilio =models.TextField(blank=True)

	def __str__(self):
		return '{} {}'.format(self.nombre, self.apellidos)

class Solicitud(models.Model):
	persona = models.ForeignKey(Persona)
	numero_mascotas = models.IntegerField()
	razones = models.TextField(null=True, blank=True)

apps/adopcion/forms.py
# -*- encoding:utf-8 -*-
from django import forms

from apps.adopcion.models import Persona, Solicitud


class PersonaForm(forms.ModelForm):
    class Meta:
        model = Persona
        fields = [
            'nombre',
            'apellidos',
            'edad',
            'telefono',
            'correo',
            'domicilio',
        ]
        labels = {
            'nombre': 'Nombre',
            'apellidos': 'Apellidos',
            'edad': 'Edad',
            'telefono': 'Teléfono',
            'correo': 'Correo electrónico',
            'domicilio': 'Domicilio',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellidos': forms.TextInput(attrs={'class': 'form-control'}),
            'edad': forms.TextInput(attrs={'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),
            'correo': forms.TextInput(attrs={'class': 'form-control'}),
            'domicilio': forms.Textarea(attrs={'class': 'form-control'}),
        }


class SolicitudForm(forms.ModelForm):
    class Meta:
        model = Solicitud
        fields = [
            'numero_mascotas',
            'razones',
        ]
        labels = {
            'numero_mascotas': 'Numero de mascotas',
            'razones': 'Razones para adoptar',

        }
        widgets = {
            'numero_mascotas': forms.TextInput(attrs={'class': 'form-control'}),
            'razones': forms.Textarea(attrs={'class': 'form-control'}),
        }

apps/adopcion/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from apps.adopcion.models import Persona, Solicitud
from apps.adopcion.forms import PersonaForm, SolicitudForm

# Create your views here.
from django.http import HttpResponse

def index(request):
    return render(request,'adopcion/index.html')

class SolicitudList(ListView):
    model = Solicitud
    template_name = 'adopcion/solicitud_list.html'

    def get_queryset(self):
        return super(SolicitudList, self).get_queryset().order_by('id')


class SolicitudCreate(CreateView):
    model = Solicitud
    template_name = 'adopcion/solicitud_form.html'
    form_class = SolicitudForm
    second_form_class = PersonaForm
    success_url = reverse_lazy('adopcion:solicitud_listar')
    #object = None

    def get_context_data(self, **kwargs):
        context = super(SolicitudCreate, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(self.request.GET)
        return context

    def post(self, request, *args, **kwargs):
        #import pdb; pdb.set_trace();
        self.object = self.get_object
        form = self.form_class(request.POST)
        form2 = self.second_form_class(request.POST)
        if form.is_valid() and form2.is_valid():
            solicitud = form.save(commit=False)
            solicitud.persona = form2.save()
            solicitud.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form, form2=form2))


class SolicitudUpdate(UpdateView):
    model = Solicitud
    second_model = Persona
    template_name = 'adopcion/solicitud_form.html'
    form_class = SolicitudForm
    second_form_class = PersonaForm
    success_url = reverse_lazy('adopcion:solicitud_listar')


    def get_context_data(self, **kwargs):
        context = super(SolicitudUpdate, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk', 0)
        solicitud = self.model.objects.get(id=pk)
        persona = self.second_model.objects.get(id=solicitud.persona_id)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class(instance=persona)
            context['id'] = pk
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        id_solicitud = kwargs['pk']
        solicitud = self.model.objects.get(id=id_solicitud)
        persona = self.second_model.objects.get(id=solicitud.persona_id)
        form = self.form_class(request.POST, instance=solicitud)
        form2 = self.second_form_class(request.POST, instance=persona)
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form,form2=form2))


class SolicitudDelete(DeleteView):
    model = Solicitud
    template_name = 'adopcion/solicitud_delete.html'
    success_url = reverse_lazy('adopcion:solicitud_listar')

apps/templates/adopcion/index.html
{% extends 'base/base.html' %}
{% block header %}header de adopcion {% endblock %}
{% block title %}ADOPCION {% endblock %}

apps/templates/adopcion/solicitud_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar la solicitud de {{ object.persona.nombre }}{{ object.persona.apellidos }}?</h3>	
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-default" href="{% url 'adopcion:solicitud_listar' %}">Cancelar</a>
</form>
{% endblock %}

apps/templates/adopcion/solicitud_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form2.nombre.name}}">{{form2.nombre.label}}</label>
				{{form2.nombre}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form2.nombre.apellidos}}">{{form2.apellidos.label}}</label>
				{{form2.apellidos}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form2.edad.name}}">{{form2.edad.label}}</label>
				{{form2.edad}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form2.correo.name}}">{{form2.correo.label}}</label>
				{{form2.correo}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form2.telefono.name}}">{{form2.telefono.label}}</label>
				{{form2.telefono}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form2.domiclio.name}}">{{form2.domicilio.label}}</label>
				{{form2.domicilio}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.numero_mascotas.name}}">{{form.numero_mascotas.label}}</label>
				{{form.numero_mascotas}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.razones.name}}">{{form.razones.label}}</label>
				{{form.razones}}
			</div>
		</div>
	</div>
	<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary" type="submit">Guardar</button>
			</div>
		</div>
	</form>
{% endblock %}

apps/templates/adopcion/solicitud_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td class="text-center">No. Solicitud</td>
			<td class="text-center">Adoptante</td>
			<td class="text-center">Edad</td>
			<td class="text-center">Telefono</td>
			<td class="text-center">Correo</td>
			<td class="text-center">Dirección Fisica</td>
			<td class="text-center">No. Mascotas</td>
			<td class="text-center">Razones</td>
			<td class="text-center">Acciones</td>
		</tr>
		
	</thead>
	<tbody>
		{% if object_list %}
		{% for solicitud in object_list %}
		<tr>
			<td class="text-center">{{ solicitud.id }}</td>
			<td class="text-center">{{ solicitud.persona.nombre }} {{solicitud.persona.apellidos}}</td>
			<td class="text-center">{{ solicitud.persona.edad }} </td>
			<td class="text-center">{{ solicitud.persona.telefono }} </td>
			<td class="text-center">{{ solicitud.persona.correo }} </td>
			<td class="text-center">{{ solicitud.persona.domicilio}} </td>
			<td class="text-center">{{ solicitud.numero_mascotas }}</td>
			<td class="text-center"	>{{ solicitud.razones }}</td>
			
			<td>
				<a class="btn btn-primary" href="{% url 'adopcion:solicitud_editar' solicitud.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'adopcion:solicitud_eliminar' solicitud.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
		
		{% else %}
		<h1>No hay registros de solicitudes</h1>
		{% endif %}

	</tbody>
</table>
<a button class="btn btn-primary" href="{% url 'adopcion:solicitud_crear' %}">Crear </button></td></a>

{% endblock%}